[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.28"
auto_detect_solc = false
evm_version = "paris"
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./test/tmp" },
]

[dependencies]
forge-std = { version = "1.15.0", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_15_0_27-02-2026_08:26:17_forge-std-1.15.zip" }
"@openzeppelin-contracts" = "5.3.0"

[rpc_endpoints]
local = "http://127.0.0.1:8545"
testnet = "${TESTNET_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
