import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SOURCE_PATH = resolve(ROOT, "AGENTS.md");
const OUTPUT_PATH = resolve(ROOT, ".cursor/rules/agents-mirror.mdc");

const RELATIONSHIP_NOTE =
	"<!-- AUTO-GENERATED — do not edit directly. Source of truth: AGENTS.md. Regenerate with `pnpm cursor-rules:sync`. -->";

/**
 * Wraps AGENTS.md's content in Cursor's `.mdc` rule format. This is a mirror,
 * not a symlink (Cursor's frontmatter has no equivalent in AGENTS.md), so the
 * relationship to the source is stated in-file and enforced by
 * scripts/check-cursor-rules.test.ts rather than by the filesystem.
 */
export function renderCursorRulesMirror(agentsMd: string): string {
	const frontmatter = [
		"---",
		"description: Mirror of AGENTS.md (the unified agent-instruction source of truth) for Cursor and other non-Claude coding agents. Do NOT edit this file directly — edit AGENTS.md, then run `pnpm cursor-rules:sync` to regenerate.",
		"alwaysApply: true",
		"---",
	].join("\n");

	return `${frontmatter}\n\n${RELATIONSHIP_NOTE}\n\n${agentsMd}`;
}

function main(): void {
	const agentsMd = readFileSync(SOURCE_PATH, "utf8");
	writeFileSync(OUTPUT_PATH, renderCursorRulesMirror(agentsMd));
}

if (import.meta.url === `file://${process.argv[1]}`) {
	main();
}
